### ISSUE TITLE
Is the Image Blurry?

### ISSUE THREAD

**Issue by jakeisnt** [sandboxnu/ELISA#2]
# Motivation
If a user is scanning in their ELISA plate, we need to ensure that the image isn't blurry so that colors aren't blending together and we can more easily identify the vials in the image. We'd like to warn the end user of blurry images and their inability to provide proper data to the end user before they take the image. 

# Task
Utilizing OpenCV, write a Python script to read in an image file and determine whether the image is blurry. This can be done in multiple ways; [this post](https://stackoverflow.com/questions/7765810/is-there-a-way-to-detect-if-an-image-is-blurry#7766036) suggests doing some cool math, while [this link](https://www.pyimagesearch.com/2015/09/07/blur-detection-with-opencv/) seems to have an implementation close to what we're looking for (though we probably want our algorithm to have a lower tolerance).  

# Logistics
Essentially, the code can be some function that accepts an image, or the file name associated with an image, and outputs true or false - whether the image is blurry or not for some definition of blurriness.

**Comment by arkinmukherjee** [comment]
PR is ready at #11

**Comment by jakeisnt** [comment]
PR merged
